### ISSUE TITLE
Document how to use this module using HTTPS

### ISSUE THREAD

**Issue by balonik** [clowdhaus/terraform-aws-eks-migrate-v19-to-v20#1]
**Describe the bug**
Using Git:SSH requires for the local environment to have a SSH Key setup and linked to a GitHub user. This is often not the case for CI environments.

Add documentation or update existing documentation to use HTTPS as source for the module.

**To Reproduce**
Define module in Terraform code:
```
module "eks" {
  source  = "git@github.com:clowdhaus/terraform-aws-eks-v20-migrate.git?
ref=c356ac8ec211604defaaaad49d27863d1e8a1391"
}
```

Run `terraform init`:
```
Error: Failed to download module
│ 
│   on main.tf line 29:
│   29: module "eks" {
│ 
│ Could not download module "eks" (main.tf:29) source code from "git::ssh://git@github.com/clowdhaus/terraform-aws-eks-v20-migrate.git?ref=c356ac8ec211604defaaaad49d27863d1e8a1391": error downloading
│ 'ssh://git@github.com/clowdhaus/terraform-aws-eks-v20-migrate.git?ref=c356ac8ec211604defaaaad49d27863d1e8a1391': /usr/bin/git exited with 128: Cloning into '.terraform/modules/eks'...
│ git@github.com: Permission denied (publickey).
│ fatal: Could not read from remote repository.
│ 
│ Please make sure you have the correct access rights
│ and the repository exists.
```

**Expected behavior**
Documentation provides a working steps/example.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

`source  = "github.com/clowdhaus/terraform-aws-eks-v20-migrate.git?ref=c356ac8ec211604defaaaad49d27863d1e8a1391"` can be used in examples instead.

**Comment by bryantbiggs** [comment]
I think that is left up to users and how they use git/GitHub
