### ISSUE TITLE
The hash of the module version in the README is not clear

### ISSUE THREAD

**Issue by igoratencompass** [clowdhaus/terraform-aws-eks-migrate-v19-to-v20#5]
**Describe the bug**

In the step 2 we have:
```
module "eks" {
-  source  = "terraform-aws-modules/eks/aws"
-  version = "~> 19.21"
+  source  = "git@github.com:clowdhaus/terraform-aws-eks-v20-migrate.git?ref=3f626cc493606881f38684fc366688c36571c5c5"
}
```
and in step 5 we have:
```
module "eks" {
-  source  = "git@github.com:clowdhaus/terraform-aws-eks-v20-migrate.git?ref=c356ac8ec211604defaaaad49d27863d1e8a1391"
+  source  = "terraform-aws-modules/eks/aws"
+  version = "~> 20.0"
}
```
Which one is the correct one?

**Comment by jatinmehrotra** [comment]
Hello @igoratencompass 

Thank you for bringing this up 

I fixed the readme as it had one-month-old hash in my[ previous MR](https://github.com/clowdhaus/terraform-aws-eks-migrate-v19-to-v20/pull/4). I forgot to update in step 5. I will fix it with another PR 


Step 2 hash is the correct one
```
module "eks" {
-  source  = "terraform-aws-modules/eks/aws"
-  version = "~> 19.21"
+  source  = "git@github.com:clowdhaus/terraform-aws-eks-v20-migrate.git?ref=3f626cc493606881f38684fc366688c36571c5c5"
}
```

**Comment by jatinmehrotra** [comment]
Will be fixed in https://github.com/clowdhaus/terraform-aws-eks-migrate-v19-to-v20/pull/6
